### ISSUE TITLE
Select columns dynamically for results

### ISSUE THREAD

**Issue by sharvaibhav** [sharvaibhav/finder-local#3]
### Abstract:
We have partially implemented a frontend solution for Finder, which helps users search through their data. We need to add a feature that allows users to dynamically select the columns they wish to see in the result section.

### Tasks:

- [ ]  Modify a UI component for column selection. This could be a drop down component which we have already created.
- [ ]  Use the metadata API to fetch available columns for selection.
- [ ]  Implement the logic to dynamically render columns based on user selection.

In the below snapshot you can see there is no way we can select which columns we need to see in the search result list.

We can try to place the column selection component just above the results component pinned to top-right. 

<img width="1254" alt="Screenshot 2023-08-30 at 12 14 46" src="https://github.com/Aize-Public/finder-react/assets/25086564/fbf1a589-64be-4012-ac14-3ba09acc0611">

**Comment by sharvaibhav** [comment]
This feature was implemented as part of some other commits, will make sure make features by following the gitflow.
