### ISSUE TITLE
Store last search state in local-storage

### ISSUE THREAD

**Issue by sharvaibhav** [sharvaibhav/finder-local#4]
### Abstract:
The Finder currently resets the filter when we re-load, this makes the user loose the currently selected filters. We want to enable to store the last updated search state in the local storage

### Tasks:

- [ ] Create a model to store the serach state
- [ ] Create a functionality to store the search state model in localstorage.
- [ ] Create functionality to do it on every filter change actions.
- [ ] Add functionality to update the filters on boostrapping time with last used filter state

The above functionality can help get the last used filter state, we can look for functionality if time allows to reset the filters state altogether.
